server:
  port: 8080
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Crawler
    username: postgres
    password: postgres
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher